Repository 9oormthon-univ/2024_DANPOON_TEAM_25_FE, pull requests merged in 2024-11, with the labels that each got.

#14 [Feature] Footer UI 구현
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Text.tsx
  src/components/layout/Footer/Footer.stories.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Hero.tsx
  src/pages/index.tsx
Labels: enhancement, UI/UX

#13 [Setting] Dockerfile, Jenkinsfile 생성
  Dockerfile
  Jenkinsfile
  next.config.js
Labels: setting

#16 [Feature] 개인정보 처리방침 페이지 UI
  src/components/layout/Policy/Policy.stories.tsx
  src/components/layout/Policy/Policy.tsx
  src/constants/privacyPolicy.tsx
  src/pages/privacy.tsx
Labels: enhancement, UI/UX

#18 [Feature] 이용 약관 페이지 UI
  src/components/layout/Footer/Footer.tsx
  src/constants/termsOfService.tsx
  src/pages/terms.tsx
Labels: enhancement, UI/UX

#20 [Feature] 로그인/회원가입 페이지 UI
  README.md
  public/google.svg
  public/kakao.svg
  public/mentee.svg
  public/mentor.svg
  public/naver.svg
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Card.tsx
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Feature.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Hero.tsx
  src/components/layout/Preview.tsx
  src/constants/Card.tsx
  src/constants/termsOfService.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/terms.tsx
Labels: enhancement, UI/UX

#26 [Feature] 수업 등록 페이지 구성요소 UI
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/LoginButton.stories.tsx
  src/components/common/Button/LoginButton.tsx
  src/components/common/Button/StartButton.stories.tsx
  src/components/common/Button/StartButton.tsx
  src/components/common/Button/TextButton.stories.tsx
  src/components/common/Button/TextButton.tsx
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Card/CharacterCard.stories.tsx
  src/components/common/Card/CharacterCard.tsx
  src/components/common/Card/PreviewCard.stories.tsx
  src/components/common/Card/PreviewCard.tsx
  src/components/common/Dropdown/Dropdown.stories.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.tsx
  src/components/layout/CourseForm/CourseForm.stories.tsx
  src/components/layout/CourseForm/CourseForm.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Hero.tsx
  src/components/layout/NewCourseBox/NewCourseBox.stories.tsx
  src/components/layout/NewCourseBox/NewCourseBox.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: enhancement, UI/UX

#28 [Feature] PageHeader UI
  src/components/common/Badge.tsx
  src/components/common/Badge/NewBadge.stories.tsx
  src/components/common/Badge/NewBadge.tsx
  src/components/common/Badge/RoleBadge.stories.tsx
  src/components/common/Badge/RoleBadge.tsx
  src/components/common/Badge/StatusBadge.stories.tsx
  src/components/common/Badge/StatusBadge.tsx
  src/components/common/Button/BackButton.stories.tsx
  src/components/common/Button/BackButton.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/EditButton.stories.tsx
  src/components/common/Button/EditButton.tsx
  src/components/common/Button/InviteButton.stories.tsx
  src/components/common/Button/InviteButton.tsx
  src/components/common/Button/NotificationButton.stories.tsx
  src/components/common/Button/NotificationButton.tsx
  src/components/common/Card/RoleCard.stories.tsx
  src/components/common/Card/RoleCard.tsx
  src/components/common/NotificationBadge/NotificationBadge.stories.tsx
  src/components/common/NotificationBadge/NotificationBadge.tsx
  src/components/layout/PageHeader/PageHeader.stories.tsx
  src/components/layout/PageHeader/PageHeader.tsx
  src/components/sidebar/ProfileSection.tsx
  src/constants/Card.tsx
  src/pages/signup/index.tsx
  src/types/sidebar.ts
Labels: enhancement, UI/UX

#33 [Feature] 선생님용 수업(Course) 목록 조회 대시보드 UI 퍼블리싱
  src/components/sidebar/TeacherSidebar.tsx
  src/pages/teacher/courses/index.tsx
Labels: enhancement, UI/UX

#36 [Feature] 선생님용 수업 생성(개설) 페이지 UI 퍼블리싱
  src/components/common/Dropdown/Dropdown.tsx
  src/components/layout/CourseForm/CourseForm.tsx
  src/components/layout/NewCourseBox/NewCourseBox.stories.tsx
  src/components/layout/NewCourseBox/NewCourseBox.tsx
  src/components/layout/PageHeader/PageHeader.tsx
  src/pages/teacher/courses/create/index.tsx
Labels: enhancement, UI/UX

#38 [Feature] 선생님용 수업(Course) 등록 완료 페이지 구성요소 컴포넌트 구현 및 페이지 퍼블리싱
  src/components/common/Box/CodeBox.stories.tsx
  src/components/common/Box/CodeBox.tsx
  src/components/common/Button/CopyButton.stories.tsx
  src/components/common/Button/CopyButton.tsx
  src/components/common/Button/InviteButton.stories.tsx
  src/components/common/Button/InviteButton.tsx
  src/pages/teacher/courses/create/complete.tsx
Labels: enhancement, UI/UX

#46 [Feature] 워크/트레이닝 상세페이지 구성요소 컴포넌트 구현 및 페이지 퍼블리싱
  src/components/common/Button/AddButton.stories.tsx
  src/components/common/Button/AddButton.tsx
  src/components/common/Button/EditButton.tsx
  src/components/common/Button/InviteButton.tsx
  src/components/common/Card/StatsCard.stories.tsx
  src/components/common/Card/SummaryCard.stories.tsx
  src/components/common/Card/SummaryCard.tsx
  src/components/common/Search/Search.tsx
  src/components/layout/PageHeader/PageHeader.tsx
  src/components/layout/Submission/SubmissionItem.stories.tsx
  src/components/layout/Submission/SubmissionItem.tsx
  src/components/layout/Submission/SubmissionStatus.stories.tsx
  src/components/layout/Submission/SubmissionStatus.tsx
  src/components/layout/Task/TaskItem.stories.tsx
  src/components/layout/Task/TaskItem.tsx
  src/components/layout/Work/WorkStatus.tsx
  src/components/layout/WorkTrainingTabs/WorkTrainingTabs.stories.tsx
  src/components/layout/WorkTrainingTabs/WorkTrainingTabs.tsx
  src/data/submissionData.ts
  src/data/taskData.ts
  src/pages/teacher/courses/[courseId]/index.tsx
  src/pages/teacher/courses/[courseId]/trainings/[trainingId]/index.tsx
  src/pages/teacher/courses/[courseId]/works/[workId]/index.tsx
  src/pages/teacher/courses/create/complete.tsx
Labels: enhancement, UI/UX

#61 [Feature] 워크(work) 상세 및 과제 제출 페이지 컴포넌트 구현
  src/components/common/Card/CommentCard.stories.tsx
  src/components/common/Card/CommentCard.tsx
  src/components/common/Card/FileUploadCard.stories.tsx
  src/components/common/Card/FileUploadCard.tsx
  src/components/common/Card/WorkInfoCard.stories.tsx
  src/components/common/Card/WorkInfoCard.tsx
  src/components/sidebar/Sidebar.stories.tsx
  src/pages/student/courses/[courseId]/works/[workId]/index.tsx
Labels: enhancement, UI/UX

#62 [Design] StudentSidebar 색상 변경
  src/components/common/Badge/RoleBadge.tsx
  src/components/common/Button/PracticeButton.tsx
  src/components/common/Card/AddCard.tsx
  src/components/common/Card/CourseCard.tsx
  src/components/sidebar/MenuItemButton.tsx
  src/components/sidebar/Navigation.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/StudentSidebar.tsx
  src/components/sidebar/TeacherSidebar.tsx
  src/pages/student/courses/[courseId]/index.tsx
  src/pages/student/courses/index.tsx
  src/types/card.ts
  src/types/sidebar.ts
  tailwind.config.js
Labels: enhancement, UI/UX

#65 [Feature] 선생님용 개별 수업 상세페이지 하단에 워크/트레이닝 생성 버튼 추가 구현
  src/components/common/Button/AddButton.tsx
  src/pages/teacher/courses/[courseId]/index.tsx
Labels: enhancement, UI/UX

#69 [Feature] Custom 404 페이지 구현
  src/pages/404.tsx
Labels: enhancement
